name: openapi_generator_annotations
description: Annotation package for openapi_generator https://pub.dev/packages/openapi_generator.
version: 1.1.2
homepage: https://github.com/gibahjoe/openapi-generator-dart


environment:
  sdk: '>=2.7.0 <3.0.0'

dev_dependencies:
  pedantic: ^1.9.2
  test: ^1.15.4
