name: openapi_generator_annotations
description: Annotation package for openapi_generator https://pub.dev/packages/openapi_generator.
version: 4.13.1
homepage: https://github.com/gibahjoe/openapi-generator-dart


environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  crypto: '>=3.0.0 <4.0.0'
  meta: '>=1.3.0 <2.0.0'
  source_gen: 

dev_dependencies:
  test:
  source_gen_test:
  lint:

dependency_overrides:
  source_gen:
    git:
      ref: reviver
      url: git@github.com:Nexushunter/source_gen.git
      path: source_gen