name: openapi_generator_annotations
description: Annotation package for openapi_generator https://pub.dev/packages/openapi_generator.
version: 3.0.0-nullsafety.1
homepage: https://github.com/gibahjoe/openapi-generator-dart


environment:
  sdk: '>=2.12.0-133.2.beta <3.0.0'

dev_dependencies:
  pedantic: ^1.10.0-nullsafety.3
  test: ^1.16.0-nullsafety.13
