name: openapi_generator_cli
description: A dart wrapper around openapi-generator inspired by the node implementation.
version: 5.0.0
homepage: https://github.com/gibahjoe/openapi-generator-dart

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  pedantic:
  test:

executables:
  openapi-generator: main
