name: openapi_generator
description: Generator for openapi client sdk inspired by the npm impplementation of openapi-generator-cli.
version: 1.1.2
homepage: https://github.com/gibahjoe/openapi-generator-dart

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  build: '>=1.3.0 <=1.10.3'
  source_gen: ^0.9.7+1
  path: ^1.7.0
  openapi_generator_annotations: ^1.1.2
  analyzer: '>=0.39.8 <=0.40.1'
  openapi_generator_cli: ^1.1.2
  generic_reader: ^0.1.5

dev_dependencies:
  pedantic: ^1.9.2
  build_config: ^0.4.2
  build_runner: '>=1.3.0 <=1.10.3'
  test: ^1.15.4
