name: openapi_generator
description: Generator for openapi client sdk inspired by the npm implementation of openapi-generator-cli.
version: 5.1.0
homepage: https://github.com/gibahjoe/openapi-generator-dart

environment:
  sdk: '>=2.15.0 <4.0.0'

dependencies:
  build: '>=1.0.0 <=3.0.0'
  source_gen: '>=1.0.0 <=2.0.0'
  path: '>=1.0.0 <=2.0.0'
  openapi_generator_annotations: '5.0.2'
  analyzer: '>=2.0.0 <7.0.0'
  openapi_generator_cli: '>5.0.2 <7.0.0'
  yaml: ^3.1.2
  http: '>=0.13.1 <=2.0.0'
  logging: '>=1.0.0 <=2.0.0'

dev_dependencies:
  test: ^1.24.2
  mockito: ^5.4.4
  build_test: '>=1.2.0 <3.0.0'
  source_gen_test:
  test_process:
  pedantic:
  coverage: ^1.6.3
