name: openapi_generator
description: Generator for openapi client sdk inspired by the npm implementation of openapi-generator-cli.
version: 2.2.0
homepage: https://github.com/gibahjoe/openapi-generator-dart

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  build: '>=1.3.0 <=1.10.3'
  source_gen: ^0.9.10+1
  path: ^1.7.0
  openapi_generator_annotations: ^2.2.0
  analyzer: '>=0.40.0 <=0.41.1'
  openapi_generator_cli: ^2.2.0

dev_dependencies:
  pedantic: ^1.9.2
  build_config: ^0.4.5
  build_runner:
  test: ^1.15.7
